### PR TITLE
[#95] Throw AuthenticationException to indicate mechanism mismatch.

### PR DESCRIPTION
**Pull request by sophokles73**
Use a subclass of `javax.security.sasl.AuthenticationException` to fail a handshake on the client side if the client does not support any of the mechanisms offered by the server.

### CODE REVIEW

**Comment by gemmellr** [comment]
Looks good, please squash the commits.

**Comment by gemmellr** [comment]
Also I dont know that there are any 3.6 releases planned, there is a 3.7 which the branch already exists for so this should probably go into master and then 3.7.

**Comment by sophokles73** [comment]
@gemmellr  Ok, shall I rebase to master then?

**Comment by gemmellr** [comment]
That would be good yes, I can then merge that and pick it into 3.7.

**Comment by sophokles73** [comment]
will do

**Pull request closed without merging**
