### PR TITLE
[#66]: Add support for OSGi

### PR DESCRIPTION
**Pull request by ctron**
This change add support for OSGi as the core vertx project provides it.

Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by vietj** [comment]
please set milestone to 3.6.0

**Comment by gemmellr** [comment]
I set it on the issue, #66.

**Comment by gemmellr** [comment]
To clarify, I didn't add it here as well in order to avoid hassle with duplicates in the release notes. Should we now add 'duplicate' to one of them to prevent that? Thats what we did in the past when the milestone wasnt used.

**Comment by vietj** [comment]
ok fine, thanks!

**Pull request merged**
