### PR TITLE
Server SASL authenticator should be pluggable.

### PR DESCRIPTION
**Pull request by hekonsek**
Hi guys,

What do you think about this pull request? It is an attempt to provide pluggable SASL authenticator to the public API of the project.

Cheers! 

/CC @gemmellr @sophokles73

### CODE REVIEW

**Comment by sophokles73** [comment]
I think this looks good, @hekonsek :-)
One little thing, though: would it make sense to pass in the `ProtonSaslAuthenticator` as part of the ` ProtonServerOptions`? This is also the place where the other security relevant options are set, e.g. server certificate etc.
What do you think?

**Comment by hekonsek** [comment]
I think that it is better to keep reference to authenticator outside of Options class, as authenticator is an external collaborator, while Option seems to be designed to hold more primitive-like values.

Robbie, what do you think?

**Comment by ppatierno** [comment]
I agree with @hekonsek on leaving the authenticator outside of the options class.

**Comment by gemmellr** [comment]
I can also see the argument for keeping it out of the options. That said, I'd maybe go for a setter on the server for a field with default value of the existing authenticator, might be simpler than all the new constructors and create calls (there are some missing create calls to go with some of those constructors otherwise).

For the tests, I think using vertx-unit like the others would be better than introducing the added dependency just for await. E.g https://github.com/vert-x3/vertx-proton/blob/master/src/test/java/io/vertx/proton/ProtonClientTest.java#L55 shows a basic enough example of that using the test context async (also note the runner on the class itself just above). 

The test also shouldn't use a hard coded port so as to avoid clashes, instead listen on 0 and ask what port was actually bound when connecting. Listen is async, might be better to use the methods with completion handler and do the connect in the callback.

I'd guess you will want additional changes beyond this once you try creating your new authenticator, so probably a good idea to do that soon.

**Comment by sophokles73** [comment]
I agree with @gemmellr regarding usage of vertx-unit. I think it provides exactly what you are looking for. No need for another tool dependency ...

@gemmellr:
When you say
> I'd guess you will want additional changes beyond this once you try creating your new authenticator, so probably a good idea to do that soon.

do you mean that we should start to implement a concrete authenticator in order to put it to a *real world* test? I would definitely agree with that :+1:

**Comment by gemmellr** [comment]
> do you mean that we should start to implement a concrete authenticator in order to put it to a real world test? I would definitely agree with that :+1:

Yep thats what I meant.

**Comment by ppatierno** [comment]
Agree with @gemmellr ... I used the vertx-unit framework for my AMQP - Kafka bridge project and it seems to work pretty well for awaiting tests.

**Comment by vietj** [comment]
hi, code freeze for 3.3.0 is this week, so this PR should be resolved soon

**Comment by hekonsek** [comment]
Used random port, migrated to Vert.x Unit and added fluent setter instead of final field and constructor.

What do you think about this version?

**Comment by gemmellr** [comment]
I had a look and the updates from before themselves look good, but in going through it again I came to realise that the additions as a whole wont actually work in their current form: while you could use this to set a new authenticator, the server couldn't actually complete accepting a connection once you did, since it is the authenticator that currently performs the final steps in the process and only the default impl would have the necessary bits needed to actually do so. Evidently I was more right than I knew when I mentioned thinking before that additional changes would be needed beyond these.

Julien is going to take a look next week with me to see what can be done.

**Comment by pmlopes** [comment]
@gemmellr please check if #25 is what was missing on this PR.

**Comment by vietj** [comment]
@gemmellr Paulo will provide support for helping you getting through this

**Comment by hekonsek** [comment]
Let's close this one then, and focus on #25. Many thanks for your help guys!

**Comment by gemmellr** [comment]
Added duplicate label to avoid the Issue and both PRs being in release notes.

**Pull request closed without merging**
